In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("raw.csv")

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group C,master's degree,standard,completed,49,100,79
1,female,group D,high school,free/reduced,none,100,64,22
2,female,group A,master's degree,free/reduced,none,82,72,66
3,male,group B,master's degree,standard,completed,100,94,90
4,female,group C,associate's degree,standard,none,86,65,60

In [4]:
df.isna().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [7]:
df.describe()

        math_score  reading_score  writing_score
count  1000.000000     1000.00000    1000.000000
mean     49.596000       48.69300      50.369000
std      29.504632       29.62753      29.376995
min       0.000000        0.00000       0.000000
25%      25.000000       23.00000      25.000000
50%      49.000000       49.00000      50.000000
75%      76.000000       74.00000      75.000000
max     100.000000      100.00000     100.000000

In [8]:
df.nunique()

gender                           2
race_ethnicity                   5
parental_level_of_education      6
lunch                            2
test_preparation_course          2
math_score                     101
reading_score                  101
writing_score                  101
dtype: int64

In [9]:
## define the numerical and the categorical value to be saparate 

numeric_features=[feature for feature in df.columns if  df[feature].dtype !='O']
categorical_features=[feature for feature in df.columns if  df[feature].dtype =='O']

## print the numerical and categorical feature 

print(f"we have {len(numeric_features)} numerical features {numeric_features}")
print(f"we have {len(categorical_features)} numerical features {categorical_features}")

we have 3 numerical features ['math_score', 'reading_score', 'writing_score']
we have 5 numerical features ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [10]:
print("Categories in 'gender' variable:     ",end=" " )
print(df['gender'].unique())

print("Categories in 'race_ethnicity' variable:  ",end=" ")
print(df['race_ethnicity'].unique())

print("Categories in'parental level of education' variable:",end=" " )
print(df['parental_level_of_education'].unique())

print("Categories in 'lunch' variable:     ",end=" " )
print(df['lunch'].unique())

print("Categories in 'test preparation course' variable:     ",end=" " )
print(df['test_preparation_course'].unique())

Categories in 'gender' variable:      ['female' 'male']
Categories in 'race_ethnicity' variable:   ['group C' 'group D' 'group A' 'group B' 'group E']
Categories in'parental level of education' variable: ["master's degree" 'high school' "associate's degree" 'some college'
 'some high school' "bachelor's degree"]
Categories in 'lunch' variable:      ['standard' 'free/reduced']
Categories in 'test preparation course' variable:      ['completed' 'none']

In [11]:
df['total score'] = df['math_score'] + df['reading_score'] + df['writing_score']
df['average'] = df['total score']/3
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total score,average
0,female,group C,master's degree,standard,completed,49,100,79,228,76.000000
1,female,group D,high school,free/reduced,none,100,64,22,186,62.000000
2,female,group A,master's degree,free/reduced,none,82,72,66,220,73.333333
3,male,group B,master's degree,standard,completed,100,94,90,284,94.666667
4,female,group C,associate's degree,standard,none,86,65,60,211,70.333333

In [12]:
reading_full = df[df['reading_score'] == 100]['average'].count()
writing_full = df[df['writing_score'] == 100]['average'].count()
math_full = df[df['math_score'] == 100]['average'].count()

print(f'Number of students with full marks in Maths: {math_full}')
print(f'Number of students with full marks in Writing: {writing_full}')
print(f'Number of students with full marks in Reading: {reading_full}')

Number of students with full marks in Maths: 14
Number of students with full marks in Writing: 12
Number of students with full marks in Reading: 13

In [13]:
reading_less_20 = df[df['reading_score'] <= 20]['average'].count()
writing_less_20 = df[df['writing_score'] <= 20]['average'].count()
math_less_20 = df[df['math_score'] <= 20]['average'].count()

print(f'Number of students with less than 20 marks in Maths: {math_less_20}')
print(f'Number of students with less than 20 marks in Writing: {writing_less_20}')
print(f'Number of students with less than 20 marks in Reading: {reading_less_20}')

Number of students with less than 20 marks in Maths: 212
Number of students with less than 20 marks in Writing: 200
Number of students with less than 20 marks in Reading: 228